apiVersion: apps/v1
kind: Deployment
metadata:
  name: algohive-cache
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algohive-cache
  template:
    metadata:
      labels:
        app: algohive-cache
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: algohive-cache
  namespace: algohive
spec:
  selector:
    app: algohive-cache
  ports:
    - port: 6379
      targetPort: 6379