# --- BEEAPI TOULOUSE ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puzzles-tlse-pvc
  namespace: algohive
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi-server-tlse
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeapi-server-tlse
  template:
    metadata:
      labels:
        app: beeapi-server-tlse
    spec:
      containers:
        - name: beeapi
          image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_NAME
              value: "Ynov-Toulouse"
            - name: SERVER_DESCRIPTION
              value: "Server for Ynov Toulouse students"
          volumeMounts:
            - name: puzzles-storage
              mountPath: /app/puzzles
      volumes:
        - name: puzzles-storage
          persistentVolumeClaim:
            claimName: puzzles-tlse-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: beeapi-server-tlse
  namespace: algohive
spec:
  selector:
    app: beeapi-server-tlse
  ports:
    - port: 5000
      targetPort: 5000

---
# --- BEEAPI MONTPELLIER ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puzzles-mpl-pvc
  namespace: algohive
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi-server-mpl
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeapi-server-mpl
  template:
    metadata:
      labels:
        app: beeapi-server-mpl
    spec:
      containers:
        - name: beeapi
          image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_NAME
              value: "Ynov-Montpellier"
          volumeMounts:
            - name: puzzles-storage
              mountPath: /app/puzzles
      volumes:
        - name: puzzles-storage
          persistentVolumeClaim:
            claimName: puzzles-mpl-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: beeapi-server-mpl
  namespace: algohive
spec:
  selector:
    app: beeapi-server-mpl
  ports:
    - port: 5000
      targetPort: 5000

---
# --- BEEAPI LYON ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puzzles-lyon-pvc
  namespace: algohive
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi-server-lyon
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeapi-server-lyon
  template:
    metadata:
      labels:
        app: beeapi-server-lyon
    spec:
      containers:
        - name: beeapi
          image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_NAME
              value: "Ynov-Lyon"
          volumeMounts:
            - name: puzzles-storage
              mountPath: /app/puzzles
      volumes:
        - name: puzzles-storage
          persistentVolumeClaim:
            claimName: puzzles-lyon-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: beeapi-server-lyon
  namespace: algohive
spec:
  selector:
    app: beeapi-server-lyon
  ports:
    - port: 5000
      targetPort: 5000

---
# --- BEEAPI STAGING ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puzzles-staging-pvc
  namespace: algohive
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi-server-staging
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeapi-server-staging
  template:
    metadata:
      labels:
        app: beeapi-server-staging
    spec:
      containers:
        - name: beeapi
          image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_NAME
              value: "Ynov-Staging"
          volumeMounts:
            - name: puzzles-storage
              mountPath: /app/puzzles
      volumes:
        - name: puzzles-storage
          persistentVolumeClaim:
            claimName: puzzles-staging-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: beeapi-server-staging
  namespace: algohive
spec:
  selector:
    app: beeapi-server-staging
  ports:
    - port: 5000
      targetPort: 5000