apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beehub-db-pvc
  namespace: algohive
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beehub
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beehub
  template:
    metadata:
      labels:
        app: beehub
    spec:
      containers:
        - name: beehub
          image: ghcr.io/algohive-coding-puzzles/beehub:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: algohive-config
            - secretRef:
                name: algohive-secret
          volumeMounts:
            - name: db-storage
              mountPath: /app/backend/db
            - name: timezone
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: beehub-db-pvc
        - name: timezone
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: beehub
  namespace: algohive
spec:
  selector:
    app: beehub
  ports:
    - port: 8081
      targetPort: 8081