apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi-server-mpl
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeapi-server-mpl
  template:
    metadata:
      labels:
        app: beeapi-server-mpl
    spec:
      containers:
        - name: beeapi
          image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_NAME
              value: "Ynov-Montpellier"
          volumeMounts:
            - name: puzzles-storage
              mountPath: /app/puzzles
      volumes:
        - name: puzzles-storage
          persistentVolumeClaim:
            claimName: puzzles-mpl-pvc