apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi-server-tlse
  namespace: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beeapi-server-tlse
  template:
    metadata:
      labels:
        app: beeapi-server-tlse
    spec:
      containers:
        - name: beeapi
          image: ghcr.io/algohive-coding-puzzles/beeapi-go:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: SERVER_NAME
              value: "Ynov-Toulouse"
            - name: SERVER_DESCRIPTION
              value: "Server for Ynov Toulouse students"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: puzzles-storage
              mountPath: /app/puzzles
      volumes:
        - name: puzzles-storage
          persistentVolumeClaim:
            claimName: puzzles-tlse-pvc